[package]
name = "attach"
version = "0.0.0"
edition = "2021"
description = "Cross platform library injector written in Rust."
license = "MIT"

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
